@startuml
left to right direction

map Gruppe.A {
Portugal=>PRT
Serbien=>SRB
Republik Irland=>IRL
Luxemburg=>LUX
}

map Gruppe.B {
Spanien=>ESP
Schweden=>SWE
Griechenland=>GRC
Georgien=>GEO
}
map Match.PRTvsSRB {
Portugal =>
Serbien =>
}

map Match.PRTvsIRL {
Portugal =>
Republik Irland =>
}

map Match.PRTvsLUX {
Portugal =>
Luxemburg =>
}

map Match.SRBvsIRL {
Serbien =>
Republik Irland =>
}

map Match.SRBvsLUX {
Serbien =>
Luxemburg =>
}

map Match.IRLvsLUX {
Republik Irland =>
Luxemburg =>
}
map Match.ESPvsSWE {
Spanien =>
Schweden =>
}

map Match.ESPvsGRC {
Spanien =>
Griechenland =>
}

map Match.ESPvsGEO {
Spanien =>
Georgien =>
}

map Match.SWEvsGRC {
Schweden =>
Griechenland =>
}

map Match.SWEvsGEO {
Schweden =>
Georgien =>
}

map Match.GRCvsGEO {
Griechenland =>
Georgien =>
}

@enduml
