@startuml TestGPTournament2.png
left to right direction

map Gruppe.A {
Lask Linz=>Lask
Real Madrid=>RM
FC Barcelona=>FCB
Manchester City=>MC
}

map Gruppe.B {
Atletico Madrid=>AM
FC Liverpool=>FCL
FC Porto=>FCP
Inter Mailand=>IM
}
map Match.RMvsMC {
Real Madrid => 2
Manchester City => 3
}

map Match.RMvsFCB {
Real Madrid => 1
FC Barcelona => 3
}

map Match.RMvsLask {
Real Madrid => 3
Lask Linz => 2
}

map Match.MCvsFCB {
Manchester City => 3
FC Barcelona => 1
}

map Match.MCvsLask {
Manchester City => 1
Lask Linz => 2
}

map Match.FCBvsLask {
FC Barcelona => 2
Lask Linz => 1
}
map Match.FCLvsFCP {
FC Liverpool => 0
FC Porto => 3
}

map Match.FCLvsIM {
FC Liverpool => 3
Inter Mailand => 1
}

map Match.FCLvsAM {
FC Liverpool => 1
Atletico Madrid => 0
}

map Match.FCPvsIM {
FC Porto => 2
Inter Mailand => 3
}

map Match.FCPvsAM {
FC Porto => 2
Atletico Madrid => 1
}

map Match.IMvsAM {
Inter Mailand => 3
Atletico Madrid => 2
}
Gruppe.A -- Match.RMvsMC
Gruppe.A -- Match.RMvsFCB
Gruppe.A -- Match.RMvsLask
Gruppe.A -- Match.MCvsFCB
Gruppe.A -- Match.MCvsLask
Gruppe.A -- Match.FCBvsLask
Gruppe.B -- Match.FCLvsFCP
Gruppe.B -- Match.FCLvsIM
Gruppe.B -- Match.FCLvsAM
Gruppe.B -- Match.FCPvsIM
Gruppe.B -- Match.FCPvsAM
Gruppe.B -- Match.IMvsAM

@enduml
