@startuml
left to right direction

scale 350 width
[*] --> IN_PREPARATION
IN_PREPARATION --> IN_PROGRESS
IN_PROGRESS --> FINISHED
IN_PROGRESS --> CANCELED
IN_PREPARATION --> CANCELED
CANCELED --> IN_PREPARATION
CANCELED --> IN_PROGRESS

state IN_PREPARATION

state IN_PROGRESS

state FINISHED

state CANCELED
@enduml