= Besprechungsprotokoll 2022.05.23
1.0, 2022.05.23
ifndef::imagesdir[:imagesdir: ../images]
:icons: font
//:sectnums:    // Nummerierung der Überschriften / section numbering
//:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// https://fontawesome.com/v4.7.0/icons/


.Teilnehmer
|===
|anwesend

|Christoph Handel

|Lukas Baumgartner

|Joachim Pelzeder

|Thomas W. Stütz

|===

.Ort und Zeit
[cols=2*]
|===
|Ort
|HTL Leonding

|von-bis
|10:00
|Dauer
|50 min
|===

== Besprochene Themen

Zwischenergebnisse müssen auch angezeigt werden

Basically nach jedem Match

Gewinner displayen bzw auswerten im Gesamten

Turniervorbereitung/erstellung > Durchführung > Auswertung

Aktivitätsdiagramm - Ablauf

Use-Case Diagram auf Gh-Pages

Ergebnisse eingeben nicht auswerten

Gh-Pages -> Für den und den Fall gibts den und den Test und das und das wird geprüft

TestSuit??? JUnit5 geht vllt nicht mehr

Wer gewonnen hat plus ein Feld mit den Punkten eventuell noch mit einem Description Feld

== Vereinbarungen und Entscheidungen

