@startuml TestGPTournament2.png
left to right direction

map Gruppe.A {
Manchester City=>MC
Inter Mailand=>IM
Manchester United=>MU
FC Barcelona=>FCB
}

map Gruppe.B {
Rapid Wien=>RW
Atletico Madrid=>AM
FC Porto=>FCP
Ajax Amsterdam=>AA
}
map Match.MCvsMU {
Manchester City => 2
Manchester United => 3
}

map Match.MCvsFCB {
Manchester City => 1
FC Barcelona => 3
}

map Match.MCvsIM {
Manchester City => 3
Inter Mailand => 2
}

map Match.MUvsFCB {
Manchester United => 3
FC Barcelona => 1
}

map Match.MUvsIM {
Manchester United => 1
Inter Mailand => 2
}

map Match.FCBvsIM {
FC Barcelona => 2
Inter Mailand => 1
}
map Match.AMvsFCP {
Atletico Madrid => 0
FC Porto => 3
}

map Match.AMvsAA {
Atletico Madrid => 3
Ajax Amsterdam => 1
}

map Match.AMvsRW {
Atletico Madrid => 1
Rapid Wien => 0
}

map Match.FCPvsAA {
FC Porto => 2
Ajax Amsterdam => 3
}

map Match.FCPvsRW {
FC Porto => 2
Rapid Wien => 1
}

map Match.AAvsRW {
Ajax Amsterdam => 3
Rapid Wien => 2
}
Gruppe.A -- Match.MCvsMU
Gruppe.A -- Match.MCvsFCB
Gruppe.A -- Match.MCvsIM
Gruppe.A -- Match.MUvsFCB
Gruppe.A -- Match.MUvsIM
Gruppe.A -- Match.FCBvsIM
Gruppe.B -- Match.AMvsFCP
Gruppe.B -- Match.AMvsAA
Gruppe.B -- Match.AMvsRW
Gruppe.B -- Match.FCPvsAA
Gruppe.B -- Match.FCPvsRW
Gruppe.B -- Match.AAvsRW

@enduml
