@startuml TestGPTournament2.png
left to right direction

map Gruppe.A {
Inter Mailand=>IM
Manchester United=>MU
FC Porto=>FCP
FC Barcelona=>FCB
}

map Gruppe.B {
Real Madrid=>RM
FC Liverpool=>FCL
Rapid Wien=>RW
Chelsea=>C
}
map Match.MUvsFCB {
Manchester United => 2
FC Barcelona => 3
}

map Match.MUvsFCP {
Manchester United => 1
FC Porto => 3
}

map Match.MUvsIM {
Manchester United => 3
Inter Mailand => 2
}

map Match.FCBvsFCP {
FC Barcelona => 3
FC Porto => 1
}

map Match.FCBvsIM {
FC Barcelona => 1
Inter Mailand => 2
}

map Match.FCPvsIM {
FC Porto => 2
Inter Mailand => 1
}
map Match.FCLvsRW {
FC Liverpool => 0
Rapid Wien => 3
}

map Match.FCLvsC {
FC Liverpool => 3
Chelsea => 1
}

map Match.FCLvsRM {
FC Liverpool => 1
Real Madrid => 0
}

map Match.RWvsC {
Rapid Wien => 2
Chelsea => 3
}

map Match.RWvsRM {
Rapid Wien => 2
Real Madrid => 1
}

map Match.CvsRM {
Chelsea => 3
Real Madrid => 2
}
Gruppe.A -- Match.MUvsFCB
Gruppe.A -- Match.MUvsFCP
Gruppe.A -- Match.MUvsIM
Gruppe.A -- Match.FCBvsFCP
Gruppe.A -- Match.FCBvsIM
Gruppe.A -- Match.FCPvsIM
Gruppe.B -- Match.FCLvsRW
Gruppe.B -- Match.FCLvsC
Gruppe.B -- Match.FCLvsRM
Gruppe.B -- Match.RWvsC
Gruppe.B -- Match.RWvsRM
Gruppe.B -- Match.CvsRM

@enduml
