@startuml TestGPTournament2.png
left to right direction

map Gruppe.A {
AC Mailand=>ACM
Ajax Amsterdam=>AA
FC Arsenal=>FCA
FC Porto=>FCP
}

map Gruppe.B {
AS Rom=>ASR
Red Bull Salzburg=>RBS
Rapid Wien=>RW
Manchester United=>MU
}
map Match.AAvsFCP {
Ajax Amsterdam => 2
FC Porto => 3
}

map Match.AAvsFCA {
Ajax Amsterdam => 1
FC Arsenal => 3
}

map Match.AAvsACM {
Ajax Amsterdam => 3
AC Mailand => 2
}

map Match.FCPvsFCA {
FC Porto => 3
FC Arsenal => 1
}

map Match.FCPvsACM {
FC Porto => 1
AC Mailand => 2
}

map Match.FCAvsACM {
FC Arsenal => 2
AC Mailand => 1
}
map Match.RBSvsRW {
Red Bull Salzburg => 0
Rapid Wien => 3
}

map Match.RBSvsMU {
Red Bull Salzburg => 3
Manchester United => 1
}

map Match.RBSvsASR {
Red Bull Salzburg => 1
AS Rom => 0
}

map Match.RWvsMU {
Rapid Wien => 2
Manchester United => 3
}

map Match.RWvsASR {
Rapid Wien => 2
AS Rom => 1
}

map Match.MUvsASR {
Manchester United => 3
AS Rom => 2
}
Gruppe.A -- Match.AAvsFCP
Gruppe.A -- Match.AAvsFCA
Gruppe.A -- Match.AAvsACM
Gruppe.A -- Match.FCPvsFCA
Gruppe.A -- Match.FCPvsACM
Gruppe.A -- Match.FCAvsACM
Gruppe.B -- Match.RBSvsRW
Gruppe.B -- Match.RBSvsMU
Gruppe.B -- Match.RBSvsASR
Gruppe.B -- Match.RWvsMU
Gruppe.B -- Match.RWvsASR
Gruppe.B -- Match.MUvsASR

@enduml
