@startuml
left to right direction

scale 350 width
[*] --> IN_PREPERATION
IN_PREPERATION --> IN_PROGRESS
IN_PROGRESS --> FINISHED
IN_PROGRESS --> CANCELED
IN_PREPERATION --> CANCELED
CANCELED --> IN_PREPERATION
CANCELED --> IN_PROGRESS

state IN_PREPERATION

state IN_PROGRESS

state FINISHED

state CANCELED
@enduml