@startuml

[*] --> IN_PREPARATION : Turnier erstellen

IN_PREPARATION --> READY : Matches setzten

READY --> IN_PROGRESS : Erstes Matchergebnis eintragen

READY <-- IN_PROGRESS : Turnier abbrechen

IN_PROGRESS --> FINISHED : Turnier auswerten

state IN_PREPARATION

state READY

state IN_PROGRESS

state FINISHED

@enduml